-- Campo Hoy: núcleo multi-organización, sincronización idempotente y auditoría.
create extension if not exists pgcrypto;
create type public.app_role as enum ('owner','manager','operator','veterinarian','advisor','readonly');
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.farms (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete restrict, name text not null, settings jsonb not null default '{}', created_at timestamptz not null default now(), unique(organization_id,name));
create table public.memberships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, farm_id uuid references public.farms on delete cascade, user_id uuid not null references auth.users on delete cascade, role public.app_role not null, active boolean not null default true, created_at timestamptz not null default now(), unique(user_id,organization_id,farm_id));
create table public.records (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete restrict,
 farm_id uuid not null references public.farms on delete restrict, entity_type text not null, event_at timestamptz not null,
 payload jsonb not null default '{}', status text not null default 'active', origin text not null default 'manual', sync_id uuid not null,
 device_id text, sync_status text not null default 'synced', created_by uuid references auth.users, updated_by uuid references auth.users,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz, notes text,
 version integer not null default 1, unique (organization_id, sync_id)
);
create index records_farm_entity_event_idx on public.records(farm_id,entity_type,event_at desc) where deleted_at is null;
create table public.audit_log (id bigint generated always as identity primary key, organization_id uuid not null, farm_id uuid, table_name text not null, record_id uuid, action text not null, old_values jsonb, new_values jsonb, actor_id uuid, occurred_at timestamptz not null default now());
create table public.analytics_sessions (id uuid primary key default gen_random_uuid(), anonymous_visitor_id uuid not null, demo_code text, user_id uuid, organization_id uuid, farm_id uuid, started_at timestamptz not null default now(), last_activity_at timestamptz, ended_at timestamptz, device_type text, browser text, screen_size text, referrer text, utm_source text, utm_medium text, utm_campaign text, created_at timestamptz not null default now());
create table public.analytics_events (id uuid primary key default gen_random_uuid(), session_id uuid references public.analytics_sessions on delete cascade, anonymous_visitor_id uuid not null, user_id uuid, organization_id uuid, farm_id uuid, event_name text not null, module text, entity_type text, entity_id uuid, screen_name text, event_properties jsonb not null default '{}', occurred_at timestamptz not null default now(), sync_status text not null default 'synced', created_at timestamptz not null default now());
create table public.demo_feedback (id uuid primary key default gen_random_uuid(), session_id uuid references public.analytics_sessions, demo_code text, rating smallint check(rating between 1 and 5), most_useful_feature text, missing_feature text, main_problem text, would_use_with_real_data boolean, would_request_demo boolean, would_pay boolean, estimated_herd_size integer, comments text, contact_requested boolean not null default false, created_at timestamptz not null default now());
create table public.commercial_leads (id uuid primary key default gen_random_uuid(), session_id uuid references public.analytics_sessions, demo_code text, first_name text not null, last_name text, phone text, email text, farm_name text, estimated_herd_size integer, message text, contact_status text not null default 'new', utm_source text, utm_campaign text, consent_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(phone is not null or email is not null));
create or replace function public.is_farm_member(org uuid, farm uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships m where m.user_id=auth.uid() and m.organization_id=org and m.active and (m.farm_id is null or m.farm_id=farm)) $$;
create or replace function public.can_write_farm(org uuid, farm uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships m where m.user_id=auth.uid() and m.organization_id=org and m.active and (m.farm_id is null or m.farm_id=farm) and m.role <> 'readonly') $$;
alter table public.organizations enable row level security; alter table public.farms enable row level security; alter table public.memberships enable row level security; alter table public.records enable row level security; alter table public.audit_log enable row level security; alter table public.analytics_sessions enable row level security; alter table public.analytics_events enable row level security; alter table public.demo_feedback enable row level security; alter table public.commercial_leads enable row level security;
create policy records_read on public.records for select using(public.is_farm_member(organization_id,farm_id));
create policy records_insert on public.records for insert with check(public.can_write_farm(organization_id,farm_id) and created_by=auth.uid());
create policy records_update on public.records for update using(public.can_write_farm(organization_id,farm_id)) with check(public.can_write_farm(organization_id,farm_id) and updated_by=auth.uid());
create policy farms_read on public.farms for select using(public.is_farm_member(organization_id,id));
create policy memberships_self_read on public.memberships for select using(user_id=auth.uid());
create policy analytics_session_own on public.analytics_sessions for select using(user_id=auth.uid() or anonymous_visitor_id::text=current_setting('request.headers',true)::jsonb->>'x-visitor-id');
create policy analytics_event_own on public.analytics_events for select using(user_id=auth.uid() or anonymous_visitor_id::text=current_setting('request.headers',true)::jsonb->>'x-visitor-id');
